basePath: /
definitions:
  models.GenDownload:
    properties:
      expire:
        description: 过期时间
        type: integer
      uid:
        description: 文件路径
        items:
          type: string
        type: array
    required:
    - expire
    - uid
    type: object
  models.GenDownloadResp:
    properties:
      meta:
        $ref: '#/definitions/models.MetaInfo'
      uid:
        type: string
      url:
        type: string
    type: object
  models.GenUpload:
    properties:
      expire:
        description: 过期时间
        type: integer
      filePath:
        description: 文件路径
        items:
          type: string
        type: array
    required:
    - filePath
    type: object
  models.GenUploadResp:
    properties:
      path:
        type: string
      uid:
        type: string
      url:
        $ref: '#/definitions/models.UrlResult'
    type: object
  models.MD5Name:
    properties:
      md5:
        type: string
      path:
        type: string
    type: object
  models.MetaInfo:
    properties:
      dstName:
        type: string
      height:
        type: integer
      md5:
        type: string
      size:
        type: string
      srcName:
        type: string
      width:
        type: integer
    type: object
  models.MultiUrlResult:
    properties:
      merge:
        type: string
      upload:
        type: string
    type: object
  models.ResumeReq:
    properties:
      data:
        items:
          $ref: '#/definitions/models.MD5Name'
        type: array
    type: object
  models.ResumeResp:
    properties:
      md5:
        type: string
      uid:
        type: string
    type: object
  models.UrlResult:
    properties:
      multi:
        $ref: '#/definitions/models.MultiUrlResult'
      single:
        type: string
    type: object
  web.Response:
    properties:
      code:
        description: 自定义错误码
        type: integer
      data:
        description: 数据
      message:
        description: 信息
        type: string
    type: object
host: 127.0.0.1:8888
info:
  contact:
    name: qinguoyi
  title: ObjectStorageProxy
  version: "1.0"
paths:
  /api/storage/v0/checkpoint:
    get:
      consumes:
      - application/json
      description: 断点续传
      parameters:
      - description: 文件uid
        in: query
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.Response'
            - properties:
                data:
                  items:
                    type: integer
                  type: array
              type: object
      summary: 断点续传
      tags:
      - 断点续传
  /api/storage/v0/download:
    get:
      consumes:
      - application/json
      description: 下载数据
      parameters:
      - description: 文件uid
        in: query
        name: uid
        required: true
        type: string
      - description: 文件名称
        in: query
        name: name
        required: true
        type: string
      - description: 是否在线
        in: query
        name: online
        required: true
        type: string
      - description: 链接生成时间
        in: query
        name: date
        required: true
        type: string
      - description: 过期时间
        in: query
        name: expire
        required: true
        type: string
      - description: 存储桶
        in: query
        name: bucket
        required: true
        type: string
      - description: 存储名称
        in: query
        name: object
        required: true
        type: string
      - description: 签名
        in: query
        name: signature
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: 下载数据
      tags:
      - 下载
  /api/storage/v0/health:
    get:
      consumes:
      - application/json
      description: 健康检查
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: 健康检查
      tags:
      - 检查
  /api/storage/v0/link/download:
    post:
      consumes:
      - application/json
      description: 获取下载连接
      parameters:
      - description: 下载链接请求体
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/models.GenDownload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.GenDownloadResp'
              type: object
      summary: 获取下载连接
      tags:
      - 链接
  /api/storage/v0/link/upload:
    post:
      consumes:
      - application/json
      description: 初始化上传连接
      parameters:
      - description: 生成上传链接请求体
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/models.GenUpload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.GenUploadResp'
              type: object
      summary: 初始化上传连接
      tags:
      - 链接
  /api/storage/v0/ping:
    get:
      consumes:
      - application/json
      description: 测试接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: 测试接口
      tags:
      - 测试
  /api/storage/v0/proxy:
    get:
      consumes:
      - application/json
      description: 询问文件是否在当前服务
      parameters:
      - description: uid
        in: query
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: 询问文件是否在当前服务
      tags:
      - proxy
  /api/storage/v0/resume:
    post:
      consumes:
      - application/json
      description: 秒传&断点续传
      parameters:
      - description: 秒传请求体
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/models.ResumeReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/web.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.ResumeResp'
                  type: array
              type: object
      summary: 秒传&断点续传
      tags:
      - 秒传
  /api/storage/v0/upload:
    put:
      consumes:
      - multipart/form-data
      description: 上传单个文件
      parameters:
      - description: 上传的文件
        in: formData
        name: file
        required: true
        type: file
      - description: 文件uid
        in: query
        name: uid
        required: true
        type: string
      - description: md5
        in: query
        name: md5
        required: true
        type: string
      - description: 链接生成时间
        in: query
        name: date
        required: true
        type: string
      - description: 过期时间
        in: query
        name: expire
        required: true
        type: string
      - description: 签名
        in: query
        name: signature
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: 上传单个文件
      tags:
      - 上传
  /api/storage/v0/upload/merge:
    put:
      consumes:
      - multipart/form-data
      description: 合并分片文件
      parameters:
      - description: 文件uid
        in: query
        name: uid
        required: true
        type: string
      - description: md5
        in: query
        name: md5
        required: true
        type: string
      - description: 总分片数量
        in: query
        name: num
        required: true
        type: string
      - description: 文件总大小
        in: query
        name: size
        required: true
        type: string
      - description: 链接生成时间
        in: query
        name: date
        required: true
        type: string
      - description: 过期时间
        in: query
        name: expire
        required: true
        type: string
      - description: 签名
        in: query
        name: signature
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: 合并分片文件
      tags:
      - 上传
  /api/storage/v0/upload/multi:
    put:
      consumes:
      - multipart/form-data
      description: 上传分片文件
      parameters:
      - description: 上传的文件
        in: formData
        name: file
        required: true
        type: file
      - description: 文件uid
        in: query
        name: uid
        required: true
        type: string
      - description: md5
        in: query
        name: md5
        required: true
        type: string
      - description: 当前分片id
        in: query
        name: chunkNum
        required: true
        type: string
      - description: 链接生成时间
        in: query
        name: date
        required: true
        type: string
      - description: 过期时间
        in: query
        name: expire
        required: true
        type: string
      - description: 签名
        in: query
        name: signature
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: 上传分片文件
      tags:
      - 上传
swagger: "2.0"
